TeklifPanel/TeklifPanelWebUI/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using TeklifPanel.Business.Abstract;
using TeklifPanel.Core;
using TeklifPanel.Entity;
using TeklifPanelWebUI.Models;
using TeklifPanelWebUI.ViewModels;

namespace TeklifPanelWebUI.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly ICompanySettingsService _companySettingsService;
        private readonly IIbanService _ibanService;

        public CompanyController(ICompanyService companyService, ICompanySettingsService companySettingsService, IIbanService ibanService)
        {
            _companyService = companyService;
            _companySettingsService = companySettingsService;
            _ibanService = ibanService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Settings()
        {
            var companyId = HttpContext.Session.GetInt32("CompanyId") ?? default;
            if (companyId != default)
            {
                var companySettings = await _companySettingsService.GetAllCompanySettingsAsync(companyId);
                var ibans = await _ibanService.GetIbansByCompanyAsync(companyId);
                if (companySettings != null && ibans != null)
                {
                    var company = await _companyService.GetByIdAsync(companyId);
                    CompanySettingsViewModel model = new CompanySettingsViewModel()
                    {
                        Id = companyId,
                        EmailAddress = company?.Email,
                        RecipientEmail = companySettings.Where(c => c.Parameter == "AliciEmail")?.FirstOrDefault().Value,
                        EmailServerPort = companySettings.Where(c => c.Parameter == "EmailSunucuPort")?.FirstOrDefault().Value,
                        EmailServer = companySettings.Where(c => c.Parameter == "EmailSunucu")?.FirstOrDefault().Value,
                        EmailUsername = companySettings.Where(c => c.Parameter == "EmailKullaniciAdi")?.FirstOrDefault().Value,
                        EmailPassword = companySettings.Where(c => c.Parameter == "EmailParola")?.FirstOrDefault().Value,
                        Logo = companySettings.Where(c => c.Parameter == "Logo")?.FirstOrDefault().Value,
                        Logo2 = companySettings.Where(c => c.Parameter == "Logo2")?.FirstOrDefault().Value,
                        PhoneNumber = companySettings.Where(c => c.Parameter == "TelNo")?.FirstOrDefault().Value,
                        FaxNumber = companySettings.Where(c => c.Parameter == "FaxNo")?.FirstOrDefault().Value,
                        Address = companySettings.Where(c => c.Parameter == "Adres")?.FirstOrDefault().Value,
                    };
                    if (ibans.Count() > 0)
                        model.Ibans = ibans;
                    else
                        model.Ibans = new List<Iban>();
                    return View(model);
                }
                TempData["Error"] = "Ayarlar sayfası açılırken hata oluştu!";
                return Redirect("/Home/Index");
            }
            TempData["Error"] = "Ayarlar sayfası açılırken hata oluştu!";
            return Redirect("/Home/Index");
        }

        [HttpPost]
        public async Task<IActionResult> Settings(CompanySettingsViewModel settingsViewModel, IFormFile logo, IFormFile logo2, List<string> IbanTitle)
        {

            var companyId = HttpContext.Session.GetInt32("CompanyId") ?? default;
            var company = await _companyService.GetCompanyByIdAsync(companyId);
            var companySettings = await _companySettingsService.GetAllCompanySettingsAsync(companyId);

            var url = Jobs.MakeUrl(companyId + company.Name);

            company.Id = companyId;
            company.Email = settingsViewModel.EmailAddress;

            if (company.Ibans.Count() == IbanTitle.Count())
            {
                for (var i = 0; i < IbanTitle.Count(); i++)
                {
                    if (!String.IsNullOrEmpty(IbanTitle[i]) && IbanTitle[i].Contains('&'))
                    {
                        var title = IbanTitle[i].Split('&')[0];
                        var ibanNumber = IbanTitle[i].Split('&')[1];
                        if (String.IsNullOrWhiteSpace(title) || String.IsNullOrWhiteSpace(ibanNumber))
                        {
                            TempData["Error"] = "'Banka Adı' veya 'IBAN' boş bırakılamaz";
                            return RedirectToAction("Settings");
                        }

                        company.Ibans[i].IbanNumber = ibanNumber;
                        company.Ibans[i].Title = title;
                    }
                }
            }
            else
            {
                for (int i = company.Ibans.Count(); i < IbanTitle.Count(); i++)
                {
                    if (!String.IsNullOrEmpty(IbanTitle[i]) && IbanTitle[i].Contains('&'))
                    {
                        var title = IbanTitle[i].Split('&')[0];
                        var ibanNumber = IbanTitle[i].Split('&')[1];
                        if (String.IsNullOrWhiteSpace(title) || String.IsNullOrWhiteSpace(ibanNumber))
                        {
                            TempData["Error"] = "'Banka Adı' veya 'IBAN' boş bırakılamaz";
                            return RedirectToAction("Settings");
                        }

                        company.Ibans.Add(new Iban
                        {
                            CompanyId = companyId,
                            IbanNumber = ibanNumber,
                            Title = title
                        });
                    }
                }

            }

            await _companyService.UpdateAsync(company);

            companySettings.Where(c => c.Parameter == "AliciEmail").FirstOrDefault().Value = settingsViewModel?.RecipientEmail;
            companySettings.Where(c => c.Parameter == "EmailSunucuPort").FirstOrDefault().Value = settingsViewModel?.EmailServerPort;
            companySettings.Where(c => c.Parameter == "EmailSunucu").FirstOrDefault().Value = settingsViewModel?.EmailServer;
            companySettings.Where(c => c.Parameter == "EmailKullaniciAdi").FirstOrDefault().Value = settingsViewModel?.EmailUsername;
            companySettings.Where(c => c.Parameter == "EmailParola").FirstOrDefault().Value = settingsViewModel?.EmailPassword;
            if (logo != null)
                companySettings.Where(c => c.Parameter == "Logo").FirstOrDefault().Value = Jobs.UploadImage(logo, url, companyId);
            if (logo2 != null)
                companySettings.Where(c => c.Parameter == "Logo2").FirstOrDefault().Value = Jobs.UploadImage(logo2, url, companyId);
            companySettings.Where(c => c.Parameter == "TelNo").FirstOrDefault().Value = settingsViewModel?.PhoneNumber;
            companySettings.Where(c => c.Parameter == "FaxNo").FirstOrDefault().Value = settingsViewModel?.FaxNumber;
            companySettings.Where(c => c.Parameter == "Adres").FirstOrDefault().Value = settingsViewModel?.Address;

            var result = await _companySettingsService.UpdateCompanySettingAsync(companySettings);
            if (result)
            {
                TempData["Message"] = "Ayarlar güncellendi";
                return RedirectToAction("Settings");
            }

            TempData["Error"] = "Ayarlar güncellenmedi";
            return RedirectToAction("Settings");
        }

        public async Task<IActionResult> IbanDelete(int id)
        {
            var iban = await _ibanService.GetByIdAsync(id);
            if (iban == null)
                return RedirectToAction("Settings");
            var result = await _ibanService.DeleteAsync(iban);
            if (result)
            {
                TempData["Message"] = "IBAN silindi";
                return RedirectToAction("Settings");
            }

            TempData["Error"] = "Iban silinemedi";
            return RedirectToAction("Settings");

        }
    }
}

TeklifPanel/TeklifPanelWebUI/Controllers/LoginController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TeklifPanel.Business.Abstract;
using TeklifPanel.Entity;
using TeklifPanelWebUI.Models;

namespace TeklifPanelWebUI.Controllers
{
    public class LoginController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly ILogService _logService;
        private readonly ICompanyService _companyService;

        public LoginController(UserManager<User> userManager, SignInManager<User> signInManager, ILogService logService, ICompanyService companyService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logService = logService;
            _companyService = companyService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(loginModel.Email);
                if (user == null)
                {
                    TempData["AlertMessage"] = "Kullanıcı adı ya da şifre hatalı!";
                    return RedirectToAction("Index");
                }
                var result = await _signInManager.PasswordSignInAsync(user, loginModel.Password, loginModel.RememberMe, false);
                if (result.Succeeded)
                {
                    HttpContext.Session.SetString("UserId", user.Id);
                    HttpContext.Session.SetInt32("CompanyId", user.CompanyId);

                    var company = await _companyService.GetByIdAsync(user.CompanyId);

                    var log = new Log()
                    {
                        CompanyId = company.Id,
                        Company = company,
                        DateOfLogin = DateTime.Now,
                        UserEmail = user.Email,
                    };

                    await _logService.CreateAsync(log);

                    return RedirectToAction("Index", "Home");
                }
                TempData["AlertMessage"] = "Kullanıcı adı ya da şifre hatalı!";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index");
        }
    }
}

TeklifPanel/TeklifPanelWebUI/Views/Shared/Preview.cshtml
<div class="container mt-5">
    <div class="d-flex" style="justify-content: space-between;">
        <div class="span4">
            <img src="Content/images/logo/logo.png" class="mb-4">
            <address>
                <strong>DEFNE BANYO LTD. ŞTİ.</strong><br>
                <p class="mt-4">Esenkent, Muhterem Sk No:56, 34776<br> Dudullu Osb/Ümraniye/İstanbul, Türkiye</p>
            </address>
        </div>
        <div class="span4 well">
            <div class="fatura-baslik">
                ÖNİZLEME
            </div>
            <div class="fatura-no mt-4">
                <strong>Teklif No:</strong> 2202
            </div>
            <div class="tarih mt-4">
                <strong>Teklif Tarih:</strong> 22.02.20
            </div>
        </div>
    </div>

    <hr class="my-4">

    <div class="musteri-bilgi">
        <h5 class="musterifir">
            Örnek Firma
        </h5>
        <Strong>Sayın</Strong>
        <p>Ebru Yılmaz</p>
        <p class="adres">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem quia magni aliquid unde nostrum minus.
        </p>
        <div class="v-daire">
            <strong>Vergi Dairesi</strong><br>
            Gebze
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="span8 well invoice-body">
            <br>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Ürün Adı</th>
                        <th>Ürün Kodu</th>
                        <th>Ürün Adeti</th>
                        <th>KDV</th>
                        <th>Ürün Fiyatı</th>
                        <th>İskonto</th>
                        <th>İskontolu Fiyatı</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="font-weight: bold;">Demir Çelik</td>
                        <td>56421</td>
                        <td>3</td>
                        <td>%20</td>
                        <td>500₺</td>
                        <td>%10</td>
                        <td>400₺</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold;">Demir Çelik</td>
                        <td>56421</td>
                        <td>3</td>
                        <td>%20</td>
                        <td>500₺</td>
                        <td>%10</td>
                        <td>400₺</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold;">Demir Çelik</td>
                        <td>56421</td>
                        <td>3</td>
                        <td>%20</td>
                        <td>500₺</td>
                        <td>%10</td>
                        <td>400₺</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold;">Demir Çelik</td>
                        <td>56421</td>
                        <td>3</td>
                        <td>%20</td>
                        <td>500₺</td>
                        <td>%10</td>
                        <td>400₺</td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold;">Demir Çelik</td>
                        <td>56421</td>
                        <td>3</td>
                        <td>%20</td>
                        <td>500₺</td>
                        <td>%10</td>
                        <td>400₺</td>
                    </tr>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                        <td><strong>Toplam Fiyat</strong></td>
                        <td><strong>7,500.00₺</strong></td>
                    </tr>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                        <td><strong>İskontolu Fiyat</strong></td>
                        <td><strong>6,750.00₺</strong></td>
                    </tr>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                        <td><strong>Toplam KDV</strong></td>
                        <td><strong>1,350.00₺</strong></td>
                    </tr>
                    <tr>
                        <td colspan="5">&nbsp;</td>
                        <td><strong>Genel Toplam</strong></td>
                        <td><strong>8,100.00₺</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="fatura-not">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos saepe nobis libero harum nesciunt commodi.
    </div>
</div>

TeklifPanel/TeklifPanelWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="Abstract" content="" />
    <meta name="Author" content="" />
    <title>@TempData["Title"]</title>
    <!--Kelimeler Max. 5 Kelime -->
    <script src="~/js/checkInput.js"></script>
    <meta name="keywords" content="" />

    <!-- Sayfa Açıklaması Max. 115 Karakter -->
    <meta name="description" content="" />
    <meta property="og:description" content="" />
    <meta itemprop="description" content="" />
    <meta name="twitter:description" content="" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.debug.js"></script>
    @await Html.PartialAsync("_Links")
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        @*<partial name="_SolMenu" />*@
        @await Component.InvokeAsync("LeftMenu")
        <div id="content">
            <!-- Page Content  -->
            @*<partial name="_NavBar" />*@
            @await Component.InvokeAsync("NavBar")

            @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>

    @await Html.PartialAsync("_Scripts")
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

TeklifPanel/TeklifPanelWebUI/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="Abstract" content="" />
    <meta name="Author" content="" />
    <title>TTR BİLİŞİM</title>

    <!--Kelimeler Max. 5 Kelime -->
    <meta name="keywords" content="" />

    <!-- Sayfa Açıklaması Max. 115 Karakter -->
    <meta name="description" content="" />
    <meta property="og:description" content="" />
    <meta itemprop="description" content="" />
    <meta name="twitter:description" content="" />



    <!-- Favicon -->
    <link rel="icon" href="Content/images/logo/fav.png" />

    <!-- Normalize ve Reset CSS -->
    <link href="Content/files/custom/normalize.css" rel="stylesheet" />
    <link href="Content/files/custom/reset.css" rel="stylesheet" />

    <!-- Animation -->
    <link rel="stylesheet" href="Content/files/animations/animate.min.css" />

    <!-- Fancybox -->
    <link rel="stylesheet" href="content/files/fancybox/jquery.fancybox.min.css" />

    <!-- Swiper -->
    <link rel="stylesheet" href="Content/files/swiper/swiper-bundle.css" />

    <!-- Bootstrap CSS -->
    <link href="Content/files/bootstrap/bootstrap.min.css" rel="stylesheet" />

    <!-- Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">

    <!-- FA - İcon -->
    <link href="Content/files/fontawesome/css/fontawesome.css" rel="stylesheet" />
    <link href="Content/files/fontawesome/css/brands.css" rel="stylesheet" />
    <link href="Content/files/fontawesome/css/solid.css" rel="stylesheet" />

    <!-- IE10 Bug -->
    <link href="Content/files/custom/ie10-viewport-bug-workaround.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.0/assets/owl.carousel.min.css">

    <!-- Şablon CSS -->
    <link href="Content/maincss/main.css" rel="stylesheet" />


    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>


</head>

<body>

    @RenderBody()

</body>

    <!-- Bootstrap JavaScript Dosyaları -->
    <script src="Content/files/bootstrap/jquery.min.js"></script>
    <script src="Content/files/bootstrap/popper.min.js"></script>
    <script src="Content/files/bootstrap/bootstrap.min.js"></script>

    <!-- IE10 bug JS -->
    <script src="Content/files/custom/ie10-viewport-bug-workaround.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js"></script>

    <!-- Swiper -->
    <script src="Content/files/swiper/swiper-bundle.js"></script>

    <!-- Fancybox -->
    <script src="Content/files/fancybox/jquery.fancybox.min.js"></script>

    <!-- Animation & Animate -->
    <script src="Content/files/custom/wow.js"></script>
    <script>
        new WOW().init();
    </script>

    <script>
        const left = document.querySelector(".left");
        const right = document.querySelector(".right");
        const container = document.querySelector(".containers");

        left.addEventListener("mouseenter", () => {
            container.classList.add("hover-left");
        });

        left.addEventListener("mouseleave", () => {
            container.classList.remove("hover-left");
        });

        right.addEventListener("mouseenter", () => {
            container.classList.add("hover-right");
        });

        right.addEventListener("mouseleave", () => {
            container.classList.remove("hover-right");
        });

    </script>


    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });

    </script>


</html>

TeklifPanel/TeklifPanelWebUI/Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-info">
            <i class="fas fa-align-left"></i>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
        </button>
        @if (User.Identity.IsAuthenticated)
        {
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                           aria-expanded="false">@User.Identity.Name</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="ChangePassword" asp-action="PasswordEdit">Şifre Yenile</a></li>
                            <li><a class="dropdown-item" asp-controller="Login" asp-action="Logout">Çıkıs Yap</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        }
    </div>
</nav>

TeklifPanel/TeklifPanelWebUI/Views/Shared/_SolMenu.cshtml
<!-- Sidebar  -->
<nav id="sidebar">
    <div class="sidebar-header">
        <img src="/Content/images/logo/pantek-logo.png" alt="" width="100%">
    </div>

    <ul class="list-unstyled components">
        <p>
            Hoşgeldiniz Sayın
            İNFO@FİRMA.COM
        </p>
        <li>
            <a asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Anasayfa</a>
        </li>
        @if (User.IsInRole("Admin"))
        {
            <li>
                <a asp-controller="Company" asp-action="Settings"><i class="fas fa-cog"></i> Ayarlar</a>
            </li>
        }
        @if (User.IsInRole("SuperAdmin"))
        {
            <li>
                <a href="#pageSubmenu4" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-user"></i> Firmalar</a>
                <ul class="collapse list-unstyled" id="pageSubmenu4">
                    <li>
                        <a asp-controller="SuperAdmin" asp-action="CompanyList">Firma Listesi</a>
                    </li>
                    <li>
                        <a asp-controller="SuperAdmin" asp-action="CompanyCreate">Firma Oluştur</a>
                    </li>
                    @*                    <li>
                <a asp-controller="SuperAdmin" asp-action="RoleList">Rol Listesi</a>
                </li>
                <li>
                <a asp-controller="SuperAdmin" asp-action="RoleCreate">Rol Oluştur</a>
                </li>*@
                </ul>
            </li>
        }
        @if (User.IsInRole("Admin"))
        {
            <li>
                <a href="#pageSubmenu4" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fas fa-user"></i> Kullanıcılar</a>
                <ul class="collapse list-unstyled" id="pageSubmenu4">
                    <li>
                        <a asp-controller="Admin" asp-action="UserList">Kullanıcı Listesi</a>
                    </li>
                    <li>
                        <a asp-controller="Admin" asp-action="UserCreate">Kullanıcı Oluştur</a>
                    </li>
                </ul>
            </li>
        }
        @if (!User.IsInRole("SuperAdmin"))
        {
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-users"></i> Müşteriler
                </a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a asp-controller="Customer" asp-action="CustomerList">Müşteri Listesi</a>
                    </li>
                    <li>
                        <a asp-controller="Customer" asp-action="AddCustomer">Müşteri Ekle</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-box-open"></i>Ürünler
                </a>
                <ul class="collapse list-unstyled" id="pageSubmenu2">
                    <li>
                        <a href="/Product/ProductList">Ürün Listesi</a>
                    </li>
                    <li>
                        <a href="/Product/AddProduct">Ürün Ekle</a>
                    </li>
                    <li>
                        <a href="/Category/CategoryList">Kategorisi Listesi</a>
                    </li>
                    <li>
                        <a href="/Category/AddCategory">Kategorisi Ekle</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#pageSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <i class="fas fa-file-contract"></i> Teklifler
                </a>
                <ul class="collapse list-unstyled" id="pageSubmenu3">
                    <li>
                        <a href="teklifler.html">Teklif Listesi</a>
                    </li>
                    <li>
                        <a href="/Offer/AddOffer">Teklif Ekle</a>
                    </li>
                </ul>
            </li>
        }
    </ul>

</nav>