TeklifPanel/TeklifPanelWebUI/Models/ChangePassword.cs
using System.ComponentModel.DataAnnotations;

namespace TeklifPanelWebUI.Models
{
    public class ChangePassword
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Bu alan zorunludur!")]
        [DataType(DataType.Password)]
        public string OldPassword { get; set; }

        [Required(ErrorMessage = "Bu alan zorunludur!")]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [Required(ErrorMessage = "Bu alan zorunludur!")]
        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "Şifreler uyuşmuyor!")]
        public string RePassword { get; set; }
    }
}

TeklifPanel/TeklifPanelWebUI/Controllers/ChangePasswordController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TeklifPanel.Entity;
using TeklifPanelWebUI.Models;

namespace TeklifPanelWebUI.Controllers
{
    public class ChangePasswordController : Controller
    {
        private readonly UserManager<User> _userManager;

        public ChangePasswordController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult PasswordEdit()
        {
            var userId = HttpContext.Session.GetString("UserId");
            ChangePassword changePassword = new ChangePassword()
            {
                Id = userId
            };
            return View(changePassword);
        }
        [HttpPost]
        public async Task<IActionResult> PasswordEdit(ChangePassword changePassword)
        {
            
            var user = await _userManager.FindByIdAsync(changePassword.Id);
            var result = await _userManager.ChangePasswordAsync(user, changePassword.OldPassword, changePassword.NewPassword);
            if (result.Succeeded)
            {
                TempData["Message"] = "Şifreniz değiştirildi!";
                return View(new { changePassword.Id });
            }
            TempData["Hata"] = "Şifreniz değiştirilemedi!";
            return View(new { changePassword.Id });
        }
    }
}

TeklifPanel/TeklifPanelWebUI/Views/ChangePassword/PasswordEdit.cshtml
@model ChangePassword
@if (TempData["Message"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Başarılı!</strong> @TempData["Message"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>HATA!</strong> @TempData["Error"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<div class="container musteri">
    <form asp-controller="ChangePassword" asp-action="PasswordEdit" method="post">
        <input type="hidden" value="@Model.Id" name="Id" />
        <div class="form-row row">
            <div class="form-group col-lg-6 col-md-6 col-12">
                <label>Mevcut Şifreniz</label>
                <input type="text" class="form-control" placeholder="Eski Şifre" asp-for="OldPassword" />
            </div>
            <div class="form-group col-lg-6 col-md-6 col-12">
                <label>Yeni Şifrenizi Giriniz</label>
                <input type="text" class="form-control" placeholder="Yeni Şifre" asp-for="NewPassword" />
            </div>
            <div class="form-group col-lg-6 col-md-6 col-12">
                <label>Şifreyi Tekrar Girin</label>
                <input type="text" class="form-control" placeholder="Şifre Tekrarı" asp-for="RePassword" />
            </div>
        </div>
        <div>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </div>
    </form>
</div>